### ISSUE TITLE
nflgame-update-players TypeError

### ISSUE THREAD

**Issue by a-camarillo** [derek-adair/nflgame#105]
Whenever I try to `nflgame-update-players` I get this error. I'm looking through the issues on this fork and the original but I can't seem to figure out the solution.

![image](https://user-images.githubusercontent.com/58638902/72233046-e1925500-3579-11ea-9c77-f3769d1de767.png)

**Comment by jbarber3388** [comment]
I believe that the date feed is actually returning the wrong week. Maybe something on NFL API? In your screenshot, the week should be 1.

The way I got around this is by specifying the week and year directly. 

(ENV) C:\Users\jpb71\ENV\Lib\site-packages\nflgame>update_players.py --phase POST --year 2019 --week 1
Loading games for POST 2019 week 1
Downloading team rosters...
33/33 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
2/2 complete. (100.00%)
Done!

**Comment by jbarber3388** [comment]
I also had to edit the update_players.py file to not allow re-directs because I kept getting
 too many redirects error. Not sure if this is related though.

<img width="556" alt="update_players_changes" src="https://user-images.githubusercontent.com/30903060/72493882-33441500-37f0-11ea-89c7-5aef5449f3d4.png">

**Comment by jbarber3388** [comment]
See #106 for more info.

**Comment by AccidentalGuru** [comment]
I upped the DEFAULT_MAX_REDIRECTS in httplib2/__init__.py to 50 instead of 5 and it ran.

Not a great solution, but it gets the job done.

**Comment by AccidentalGuru** [comment]
Update: I installed nflgame in another env and upping the DEFAULT_MAX_REDIRECTS did not power through the update-players failure. I needed to hack update-players.py and insert 
, redirects = False
to get the update to work, but now it is complaining about JAC and SD. I don't remember where to fix that, but I'll look around old issues.

**Comment by ochawkeye** [comment]
> but now it is complaining about JAC and SD. I don't remember where to fix that, but I'll look around old issues.

Check out `teams` in `__init__.py`.  I think if you have this it should work.

```python
teams = [
    ['ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals'],
    ['ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons'],
    ['BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens'],
    ['BUF', 'Buffalo', 'Bills', 'Buffalo Bills'],
    ['CAR', 'Carolina', 'Panthers', 'Carolina Panthers'],
    ['CHI', 'Chicago', 'Bears', 'Chicago Bears'],
    ['CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals'],
    ['CLE', 'Cleveland', 'Browns', 'Cleveland Browns'],
    ['DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys'],
    ['DEN', 'Denver', 'Broncos', 'Denver Broncos'],
    ['DET', 'Detroit', 'Lions', 'Detroit Lions'],
    ['GB', 'Green Bay', 'Packers', 'Green Bay Packers', 'GNB'],
    ['HOU', 'Houston', 'Texans', 'Houston Texans'],
    ['IND', 'Indianapolis', 'Colts', 'Indianapolis Colts'],
    ['JAX', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAC'],
    ['KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs', 'KAN'],
    ['LA', 'Los Angeles', 'Rams', 'Los Angeles Rams', 'LAR'],
    ['SD', 'San Diego', 'Chargers', 'San Diego Chargers', 'SDG'],
    ['LAC', 'Los Angeles C', 'Chargers', 'Los Angeles Chargers', 'LAC'],
    ['MIA', 'Miami', 'Dolphins', 'Miami Dolphins'],
    ['MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings'],
    ['NE', 'New England', 'Patriots', 'New England Patriots', 'NWE'],
    ['NO', 'New Orleans', 'Saints', 'New Orleans Saints', 'NOR'],
    ['NYG', 'New York G', 'Giants', 'New York Giants'],
    ['NYJ', 'New York J', 'Jets', 'New York Jets'],
    ['OAK', 'Oakland', 'Raiders', 'Oakland Raiders'],
    ['PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles'],
    ['PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers'],
    ['SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks'],
    ['SF', 'San Francisco', '49ers', 'San Francisco 49ers', 'SFO'],
    ['STL', 'St. Louis', 'Rams', 'St. Louis Rams'],
    ['TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers', 'TAM'],
    ['TEN', 'Tennessee', 'Titans', 'Tennessee Titans'],
    ['WAS', 'Washington', 'Redskins', 'Washington Redskins', 'WSH'],
]
```

**Comment by derek-adair** [comment]
@ochawkeye thanks a bunch for all your help even tho you're a troglodyte on 2.7 ;-)

Really appreciate it.

**Comment by AccidentalGuru** [comment]
Nice work on the new version Derek.
I was flirting with troglodytism because 2.0.1b2 wouldn't install under Python 3,  but I could get 2.0.1b1 to work under 2.7 (even though  I don't think that is expected behavior).
I hadn't been organized enough to open an issue and hoped an update would make it just go away.
My wish was granted.

**Comment by derek-adair** [comment]
@AccidentalGuru working on nfldb right now ;)
