### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#11]
I'm thinking a docker image will be a FANTASTIC way to negate low level questions.  A lot of times a working example is all I've needed to grok a project.

It should;

- [ ] Include runnable version of tests
- [x] Include demo apps
- [x] PyPi Example
- [ ] Local build example
- [ ] demonstrate how/when requests are made to nfl.com
- [ ] A fully baked and ready to go version released via hub.docker.com

**Comment by mickeelm** [comment]
Very interesting thought! No experience of building docker images myself but cool idea. Maybe off topic but, if we someday reach a state where we'd like to bring together nflgame, nfldb, nflvid...Docker would be a great tool.

**Comment by derek-adair** [comment]
I'll be contributing this one.

**Comment by derek-adair** [comment]
Simple demo from the readme is good to go.

**Comment by derek-adair** [comment]
I have no plans on elaborating on this, may reopen later.
