### ISSUE TITLE
Get personnel by play

### ISSUE THREAD

**Issue by Plarubato** [derek-adair/nflgame#110]
Hi,

I can get players out of a play by doing:

```
g = nflgame.one(2019,1,'BAL','BAL')
for g in g.drives:
    for p in g.plays:
        print(p.players)
```

But this only gets the players involved in that play. Is there any way of getting all the players in the offensive side for each play?

I would like to calculate the personnel lineup of each play (11, 21 etc).

Thanks

**Comment by ochawkeye** [comment]
Afraid not, at least not from this API.  You are displaying every player that `nflgame`  is aware of in your code.  If they didn't record a stat, they are not generally included in the play-by-play that is the source of `nflgame`'s data.

**Comment by Plarubato** [comment]
Thanks for the clarification @ochawkeye! And thanks for getting this great API going on!
