### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#111]
Due to personal circumstances i've been unable to dedicate the time to this project that it currently deserves, and will likely be unable to do so for the next year.  

If anyone is willing/able to help contribute i'd be glad to promote someone.

**Comment by mickeelm** [comment]
Just chiming in - thank you for taking the lead on this in the first place, but also for making a clear statement that you won't have time for it anymore. Hopefully someone out there can carry the torch from now on.

**Comment by derek-adair** [comment]
Part of it is financial need as well. I have thought about crowd funding but i'm pretty sure if someone started visibly making $ off this it would increase the chances of getting sued by the nfl.

**Comment by ochawkeye** [comment]
> Part of it is financial need as well. The project i was working on has slowed down and isn't generating income for me anylonger.
> 
> I have thought about crowd funding but i'm pretty sure if someone started visibly making $ off this it would increase the chances of getting sued by the nfl.

Burntsushi warned against running this for commercial applications nearly 6 years ago.
https://github.com/BurntSushi/nflgame/issues/76#issuecomment-46744553

`nflgame` was never intended for such.

**Comment by derek-adair** [comment]
I wasn't proposing as much.  I had a privately funded project that is no longer in active development.

**Comment by samLozier** [comment]
@derek-adair  Are there any specific things you need/want help with? bugs, features, docs ?

**Comment by derek-adair** [comment]
any and all of these, yes.  Specifically;

1. Test Coverage for new 2.0 changes so I can confidently release 2.0
2. Maybe helping shift to new feed.
3. Probably lots of docs to update
4. Bug tracker is getting unruly

Probably a lot more.

**Comment by derek-adair** [comment]
I've recently been able to pick this project back up, but I still welcome any serious contributors with python exp.

**Comment by AccidentalGuru** [comment]
I have often been called jocular, and sophomoric, but I have tamed some python, and would like o help. 
Currently, I have a bit too much time.

**Comment by derek-adair** [comment]
Also currently looking to port nfldb over to python3.  [I have a branch started on my forked repo](https://github.com/derek-adair/nfldb/tree/py3).

**Comment by derek-adair** [comment]
nfldb ported
