### ISSUE TITLE
NFL Rosters Fail to Update w/o Spoofed User-Agent

### ISSUE THREAD

**Issue by keithdoggett** [derek-adair/nflgame#124]
In the `update_players` module, requests to `http://www.nfl.com/teams/roster?team=*` respond with `403 Forbidden`, currently.

I modified the master branch and if the `User-Agent` is spoofed in the request I get a `200 OK` response and everything works as expected. I'd be happy to submit a PR making this quick fix if you want to go this route.

**Comment by derek-adair** [comment]
Already had this in there, forgot to push it... releasing under 2.0.4
