### ISSUE TITLE
Python 3 Discussion

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#2]
I'm opening this issue to have an open discussion about if this is worth the effort and if so, what that may look like.  I will be updating this issue as the discussion evolves.

--------------------

Starting this off w/ a simple pro/con list as i see it... which is no doubt incomplete.

Upgrade Pros
=====
1. **Security** - This is probably my primary reason.  I've tightly coupled this into my application so its a bit concerning to be stuck on python 2.7.

2. **Newest python features** -  async stuff could be quite useful in live

Upgrade Cons
===========
1. **Work** needs to be done (lol)

------------------

Questions
=========
1. Will using python 2 to 3 work?

**Comment by benlindsay** [comment]
It sounds like a lot of packages are slowly sunsetting support for python 2, so if we want this to last any amount of time into the future I think it needs to move to python 3. I have no experience with doing that for anything bigger than small scripts though, and probably wouldn't have time to contribute if I did...

**Comment by mickeelm** [comment]
Python 2 (2.7) is  EOL as of 2020-01-01, which really isn't far from now. My suggestion, given the fresh start nature of this fork, is to move to Python 3 completely.

It might be painful for users of nflgame that have made a lot of integration with the current version and of course it would be desirable that _everybody_ can enjoy new features that possibly are added in this fork. But, the time frame for Python 2.7 is so short (and it has aldready been extended five years once...) that my opinion is that we should drop Python 2 support moving forward.

**Comment by derek-adair** [comment]
+1 on the unit tests

Not sure how useful a distinct fork would be.  A new branch will be sufficient (perhaps you didn't mean that literally).

**Comment by derek-adair** [comment]
I think there is a way to serve the old python 2.7 version if a user installs w/ python 2.7.  I'm not 100% sure though.

**Comment by Irish1986** [comment]
I am very interested in participating in this.  I have been running a "self updated" Py3 version of NFLGame for couple of years.  My main goal was to run this with Py3 to cimplify my notebook coding.

**Comment by derek-adair** [comment]
@Irish1986 FANTASTIC.  Do you have this living anywhere that we can take a look at it?

Also i'm fine w/ a complete migration to Py3 in hindsight.

**Comment by Irish1986** [comment]
@derek-adair I will clone your rep, make a new branch, update with my Py3 code and submit a PR for you to look at it.  It is not perfect but it has been working for couple of years for me.  I am fairly certain that I am missing a lot but it could be a starting point for NFLGAME3/NFLGAME-REDUX

**Comment by jnelson16** [comment]
Definitely interested in contributing to this in whatever way I can.

**Comment by Abrunacci** [comment]
how can i contribute?
