### ISSUE TITLE
Can this fork be used with nfldb? 

### ISSUE THREAD

**Issue by jlubeck** [derek-adair/nflgame#20]
I'm trying to get nfldb working but as you already know, it's broken with current season. I saw this new repo and got excited, but I see it is only handling nflgame, and not nfldb yet.  I did notice that you forked nfldb as well, but there are new commits there yet. Are you planning on updating it to work with this anytime soon?

Thanks!

**Comment by ochawkeye** [comment]
Install the forked version of `nflgame` (`pip install nflgame-redux`) and try the old `nfldb` again.  It should work.

**Comment by derek-adair** [comment]
Gonna create an FAQ and add this shortly

**Comment by derek-adair** [comment]
Closing b/c this is made aparant in the README.md now.

**Comment by jlubeck** [comment]
Thanks!
