### ISSUE TITLE
Is there an up-to-date repository that connects nflgame-redux to nfldb with all of the db value fixes?

### ISSUE THREAD

**Issue by JoeNoPhoto** [derek-adair/nflgame#26]
_Sorry as this isn't directly a nflgame issue per-se but this is the only active community that I'm aware of._

Everytime I uninstall/reinstall nfldb, I've got to re-jump through all of the hurdles to get the data updated. I know @ochawkeye is the nfldb guru, but the head of his fork isn't set up in conjunction with this either. 

Does this mythical nfldb repository exist already, because it's definitely something that should be set up if it hasn't already.

**Comment by derek-adair** [comment]
It's my understanding that if you simply install nflgame-redux after nfldb it should be a drop in replacement.

**Comment by derek-adair** [comment]
Also i'm working on digesting the entirety of the nfl* codebase developed by our lord and savior @burntsushi.  

There is a LOT.  I'll be organizing this into a group and determining the best way to go forward.

I am also considering asking for help from jazzband.co
