### ISSUE TITLE
Game time remaining

### ISSUE THREAD

**Issue by raphattack** [derek-adair/nflgame#32]
Is there a way to get the remaining game time with `nflgame`? I noticed that `nfldb` does not store this information.

**Comment by 19eddiedean19** [comment]
This is not exactly what you're asking for but thought it may help bring you in the right direction. I have a function in php to show current quarter and game time. You could calculate current gametime then subtract... 60 - ($minutesMath * $currentQuarter). 

in my scenario im doing this on a per player basis so im getting their current gsis_id, querying the most recent play from play table matching it, then returning the time column value.

 function getCurrentGametime($timestring) {
    $timestring = rtrim($timestring,')');
    $timestring = substr($timestring, 1);
    $array = explode(',', $timestring);
    $quarter = $array['0'];
    $hour = $array['1'] / 60;
    $hour = round($hour);
    $hour = 15 - $hour;
    $minutes = $array['1'] % 60;
    $minutes = 60 - $minutes;
    if ($minutes == 60) {$minutes = 0;}
    $minutes = sprintf("%02d", $minutes); 
    $time = $hour . ":" . $minutes;
    $gametime = $quarter . ' ' . $time;
    
    return $gametime;
        
}

**Comment by derek-adair** [comment]
Pretty sure not, but cataloging as an enhancement cuz that seems useful.  You are **ENCOURAGED** to dive in and submit this as a PR, and i'll get it in there.

**Comment by derek-adair** [comment]
Need to sniff out if this is in the new data streams as well (#46)

**Comment by derek-adair** [comment]
This is actually able to be inferred from the last play.time.  I dont think its realistic to expect this library to track the actual play clock.
