### ISSUE TITLE
Which branch is the active one?

### ISSUE THREAD

**Issue by MLDERES** [derek-adair/nflgame#37]
Sorry I'm a bit confused by all the copy/paste, merging and branches.  I had expected to see a branch for dev and somewhere where the dev branch merges into the main branch (where i would typically look for the latest working version).  Is this the case in this project?  It doesn't look like it given the way the branches  look to me.

**Comment by derek-adair** [comment]
If youi're referring to the copy/paste branch of Py3 version that is not going to make it into the current repository until its... not copy/paste.

Master will be all the latest changes and should reflect the latest version published in pypi.  I think i forgot to merge some things and i'm usually lazy about editing the readme.

Dev will be the main working branch where any new features or whatever are coded against.

All releases will be tagged.

I'm open to any other suggestions, i think i had some code i missed in the last update to master... so let me know if anything is unclear now.
