### ISSUE TITLE
Is there a way to get the real-world time of a play?

### ISSUE THREAD

**Issue by etsweeney** [derek-adair/nflgame#38]
I've been working on a project that shows all the plays, but I want to display them in the order in which they occurred.  Is there anything in nflgame or nfldb that has this information, or is it just not available via the JSON we parse?

The way I've been working around it is using the time_inserted value in NFLDB and making sure nflgame is running live during Sunday. But if any of my processes crash during the game, there's no way to determine when each play actually occurred in the real world.

**Comment by mickeelm** [comment]
It's not available in the game-json I'm afraid. Maybe in the NFL APIs but not in the feeds we use.

**Comment by etsweeney** [comment]
Dang, thanks!
