### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#4]
Need the ability to release improvements, either @burntsushi can hook up permissions, we can find someone who has them OR we create nflgame-redux.

I'd rather wait for burnt sushi but if something doesn't happen soon i will just use redux until we get ahold of him.

-------------------
**UPDATE:**
* I've reached out to burnt Sushi to take over the pypi listing
* I've uploaded 1.2.22-rc1 to nflgame-redux, which includes the initial 2018 schedule data.

**Comment by MikeSpitz** [comment]
Might be best to just call it something new for now, and if you do get permissions you could just close that package?

**Comment by derek-adair** [comment]
Ya i've opened nflgame-redux for now.  It includes a potentially breaking change of _CUR_SEASON

**Comment by BurntSushi** [comment]
I'd rather see new maintainers grow separate projects (possibly with nflgame as a base), so I don't have any specific plans of handing over PyPI ownership.

**Comment by mickeelm** [comment]
This is good I think, making it clearer that this isn't a project maintained by the original author/maintainer (or someone appointed by the original maintainer) but a fork. Thanks for replying on this, @BurntSushi.
