### ISSUE TITLE
Creating a full season game log

### ISSUE THREAD

**Issue by Jut254** [derek-adair/nflgame#41]
I'm trying to become familiar with this package, but am having some issues creating a full season game log (individual stats for each player for each week of the season). Here is the code I have, which seems like it _would_ work but it takes a very long time. If anybody could help that would be great

```
emptydf = pd.DataFrame(columns = uniquekeys)
week1 = 1
year1 = 2009
numrecords = 0

for y in range(year1, 2018):
  for w in range(week1, 18):
    games = nflgame.games(y,w)
    for g in games:
      hometeam = g.home
      awayteam = g.away
      for p in g.max_player_stats():
        numrecords = numrecords + 1
        playername = p.name
        playerteam = p.team
   # playerpos = p.position
    #print(type(p.stats))
        tempdf = pd.DataFrame(p.stats, index = [numrecords])
        tempdf.insert(0,'Name',playername)
        tempdf.insert(1,'Week',week)
        tempdf.insert(2,'Year',year)
        tempdf.insert(3,'Team',playerteam)
        tempdf.insert(4,'Home',hometeam)
        tempdf.insert(5,'Away',awayteam)
    #tempdf.insert(6,'Position',playerpos)
        emptydf = pd.concat([emptydf,tempdf]).fillna(0)
  print('Year % Complete' % y)
 
 ```

**Comment by ochawkeye** [comment]
Your query opens, parses, and combines the results of every player that played in the 2300+ games that occurred in the past decade.  That's going to take a long time.  I think you should try biting off a bit smaller chunck to get yourself accustomed to it.

**Comment by derek-adair** [comment]
Closing because... well... ya.
