### ISSUE TITLE
2017 Super Bowl Missing Overtime Data

### ISSUE THREAD

**Issue by cruffenach** [derek-adair/nflgame#43]
I noticed that the 2017 Super Bowl seems to be incorrect. There's no data regarding the overtime. 

```python
>>> pp.pprint(game[0].schedule)
{   u'away': u'PHI',
    u'day': 4,
    u'eid': u'2018020400',
    u'gamekey': u'57500',
    u'home': u'NE',
    u'meridiem': u'PM',
    u'month': 2,
    u'season_type': u'POST',
    u'time': u'6:30',
    u'wday': u'Sun',
    u'week': 4,
    u'year': 2017}
>>> pp.pprint(game[0].data['qtr'])
u'Final'
>>> pp.pprint(game[0].score_home_q5)
0
>>> pp.pprint(game[0].score_away_q5)
0
```

**Comment by ochawkeye** [comment]
The Super Bowl that occurred in February 2017 was for the 2016 season. 

The 2017 Super Bowl (Feb 2018) between the Eagles and Patriots was won by the Eagles in regulation.

**Comment by cruffenach** [comment]
Doh, thanks.

**Comment by cruffenach** [comment]
Wait so maybe I'm missing how to query for that game then? I'm seeing

```python
>>> pp.pprint(nflgame.games(2017, kind="POST", week=4)[0].schedule)
{   u'away': u'PHI',
    u'day': 4,
    u'eid': u'2018020400',
    u'gamekey': u'57500',
    u'home': u'NE',
    u'meridiem': u'PM',
    u'month': 2,
    u'season_type': u'POST',
    u'time': u'6:30',
    u'wday': u'Sun',
    u'week': 4,
    u'year': 2017}
```

Which seems unexpected given the following in the documentation

> The year parameter specifies the season, and not necessarily the actual year that a game was played in. For example, a Super Bowl taking place in the year 2011 actually belongs to the 2010 season. Also, the year parameter may be set to a list of seasons just like the week parameter.

**Comment by cruffenach** [comment]
Ok obviously the year is always the NFL year and not the date of the actual game. Sorry this all makes sense now.
