### ISSUE TITLE
game data for gsis_id 201709006 missing

### ISSUE THREAD

**Issue by Coach81** [derek-adair/nflgame#51]

**Comment by Coach81** [comment]
Greetings.  I recognize that BurntSushi's support of nfldb has been discontinues.  The software still seems to work, a little bit.  I ran nfldb-update and it crashed trying to do something with the game in the subject line.  I have confirmed that this game is in the 'game' table.  Any thoughts as to how to correct this?

**Comment by 19eddiedean19** [comment]
Try to delete it from the game table and re-run nfldb-update

**Comment by Coach81** [comment]
This solved my problem.  Can you help me understand why?  Thank you for your help.

**Comment by derek-adair** [comment]
my best guess is that the game data was stale and there is no mechanism for updating stale content in the database.

@19eddiedean19  (love the name btw) - is this accurate?

Closing b/c this isn't nfldb.  I will find time to bring this under my control some time soon.
