### ISSUE TITLE
Determining change week to week

### ISSUE THREAD

**Issue by JustinWise4** [derek-adair/nflgame#52]
What is the best way going about finding a "delta" between the previous two games? For example, if I want to see the change in Saquon Barkley's rushing yards from week 3 to 4 in the 2018 season, what is the best way to go about that? What about finding a delta for each week throughout the season?

**Comment by derek-adair** [comment]
There is no magic method for doing this.  I'm genuinely unsure if these types of methods belong here, but I can see this and other higher level methods being baked in being useful...  

Unfortunately, there are some rather MASSIVE changes on the horizon so any efforts towards this end would likely be a waste at the moment.

For now you can probably do[ nflgame.combine_play_stats()](https://github.com/derek-adair/nflgame/blob/master/nflgame/__init__.py#L358) and with some logic write your own method for such a thing.

**Comment by ochawkeye** [comment]
There might not be a method specifically for this, but it's pretty much built in...

Here are Saquon Barkley's stats between weeks 3 and 7:
```python
import nflgame

saquon = nflgame.find('Saquon Barkley')[0]
print saquon

games = nflgame.games(2018, week=range(3, 7+1), kind='REG', home=saquon.team, away=saquon.team)
players = nflgame.combine_max_stats(games).filter(playerid=saquon.playerid)

for player in players:
    print player, player.formatted_stats()
```
```
Saquon Barkley (RB, NYG)
S.Barkley receiving_yac_yds: 351, rushing_tds: 4, receiving_rec: 33, rushing_yds: 347, receiving_yds: 322, rushing_att: 69, receiving_tar: 39, rushing_lngtd: 68, receiving_tds: 2, receiving_twopta: 0, receiving_lng: 160, rushing_twopta: 1, rushing_lng: 147, receiving_lngtd: 57, receiving_twoptm: 0, rushing_twoptm: 1, defense_tkl: 1
```
