### ISSUE TITLE
Play by Play video nflvid-slice

### ISSUE THREAD

**Issue by davebridget** [derek-adair/nflgame#57]
I understand nflvid is not maintained but reaching out to see if anyone has been able to get 2018 video and sliced.  I have been able to download a full game coaches file but do not have the xml file. 

I have made changes to init.py to try and get the xml path for 2018.  Assuming the path is different.  Has anyone discovered a new working path?  Or is this just obsolete?   Any better ideas?

**Comment by derek-adair** [comment]
Indeed this is not the appropriate forum!  Rest assured, I have plans to unify these tools into one toolbelt and project by the end of Q1 / early Q2.  This will likely be a clean break from all of these repositories (with appropriate attribution of course), involving a massive refactor and re-organization of code.

I dont have any explicit plans, but it's quite clear these projects are married enough to be included under one roof.  I'd like to maintain as much separation as possible and maintain a configurable code base, but one bug tracker and package to download is a clear win for the community that wants to leverage this code.

If anyone would like to volunteer their time to help me plan out this work i'd be very appreciative.  I've never really refactored code on this level, so it should be a wonderful advengure!!! :)

**Comment by derek-adair** [comment]
Also this is super vague.  You need to supply references to the specific bits of code that are failing as well as some more detialed errors/symptoms.

**Comment by davebridget** [comment]
Sorry on the vagueness.  I guess when you look at something so long, you just assume everyone else knows it already.  

root@instance-1:/home/david# nflvid-slice /home/david/rams/pbp /home/david.rickman/rams/2018111900.mp4
Updating (2018, 'POST', 4)
HTTP Error 404: Not Found (http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/nflgr/2018/57727.xml)
There are no unsliced plays remaining for game (Season: 2018, Week: 11, KC at LA).
If they have not been sliced yet, then the XML play-by-play meta data may not be available or is corrupt.

modified nflvid/__init__.py to add row for 2018 using same url as 2015 identified on another issue.  

_xml_base_urls = {
    'default': 'http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/' \
            'nflgr/%d/%s.xml',
    '2018': 'http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/' \
            'nflgr/%d/%s.xml',
}

**Comment by derek-adair** [comment]
Yea, it's also because i've never ran that project.  It's a pretty neat thing, however, so it's definitely on the list of things I need to look at.

It's my understanding that nflvid uses nfldb and thus nflgame.  There were some api changes in 2018 season that broke nflgame.

- Do you have a working copy of nfldb/nflgame?
- Are you using nflgame-redux?

**Comment by davebridget** [comment]
I have a working copy nfldb/nflgame.  Plus using nflgame-redux.   Just nflvid not working.  Pretty confident that is just the URL to get the xml file is not working anymore.  NFL likely changed.

**Comment by derek-adair** [comment]
Quick question: Did you ever have nflvid working or are you a new user?

This will help me narrow down the type of bug i'm looking for.

**Comment by davebridget** [comment]
New user.  Thanks.

**Comment by derek-adair** [comment]
Also is it just this game broken or all games?

**Comment by davebridget** [comment]
All games.   I believe the slice needs a xml file to be able to properly identify the times to slice on.   Can't seem to find a source for the file to be able to download.
