### ISSUE TITLE
Calculating score during historical games

### ISSUE THREAD

**Issue by utkarshshah007** [derek-adair/nflgame#58]
Hey folks!

I'm new here, so sorry if the answer to this is obvious.

I'm trying to use `nflgame` to do some statistical analysis on historical games. Part of the analysis requires knowing the score of the game _at different times_. For instance, I need to know what the score was at halftime, and also what it was after the end of the first drive after the half.

Looking at a particular game, I can easily find the score at the end of the game. However, it doesn't seem to be recorded for individual quarters or the half. Looking at drives, I can even determine the `drive.result` (TD, punt, interception, etc). However, there isn't any data recording the actual score at the end of the drive.

I thought about calculating this myself using the `result` field of all drives that occurred before the one I'm interested in, but I noticed that the field is fairly limited. A `result` is still a TD even if the extra point is missed. I also wonder what would happen with pick-sixes, safeties, or extra points that get returned the other way.

Any ideas on how I can find this information?

**Comment by ochawkeye** [comment]
Sorry, see https://github.com/BurntSushi/nflgame/issues/342

In order to obtain what you're after, you'd need to use `nfldb` unless you wanted to calculate yourself.

**Comment by utkarshshah007** [comment]
For anyone interested, this will do a rough calculation:

```
import nflgame

def score_at_drive(drive):
    '''
    Estimates what the score was at the start of a drive.
    Warning: This is only an estimate. Doesn't properly count the following:
    - Missed extra points or 2-pt conversions
    - Defensive scoring e.g. pick-6, fumble-return-for-touchdown
    '''
    # Find the game
    game = drive.game

    # Find the score at the start of the quarter
    qtr = drive.time_start.qtr
    score = {game.home:0, game.away:0}
    for q in range(1,qtr):
        score[game.home] += getattr(game, "score_home_q" + str(q))
        score[game.away] += getattr(game, "score_away_q" + str(q))

    print ("quarter: %d" % qtr, score)

    # Add the estimated scores of all drives since the quarter started
    for drive in game.drives.filter(drive_num__lt=drive.drive_num):
        if drive.time_start.qtr == qtr:
            scores = _estimated_score_for_result(drive.result)
            if drive.team == game.home:
                score[game.home] += scores[0]
                score[game.away] += scores[1]
            else:
                score[game.away] += scores[0]
                score[game.home] += scores[1]

            print (drive.result, score)

    return score

def _estimated_score_for_result(result):
    return {
        "Touchdown": (7,0),
        "Field Goal": (3,0),
        "Safety": (0,2)
    }.get(result,(0,0))

```
@derek-adair, if this is valuable somewhere let me know and I'm happy to make a PR
