### ISSUE TITLE
Can someone help me with a simple task.  I just need to display the scores of games in a certain week and export it to excel

### ISSUE THREAD

**Issue by scockster** [derek-adair/nflgame#59]

**Comment by scockster** [comment]
nlfgame-display a week of scores and export to excel.  Help

**Comment by ochawkeye** [comment]
What have you tried?

**Comment by derek-adair** [comment]
Here's a link to the relevant docs.

[Docs](http://nflgame.derekadair.com/#nflgame.combine_plays)

**Comment by scockster** [comment]
This works for RB stats week 10 of 2018.
import nflgame

games = nflgame.games(2018, week=10)
players = nflgame.combine_game_stats(games)
for p in players.rushing().sort('rushing_yds').limit(5):
    msg = '%s %d carries for %d yards and %d TDs'
    print msg % (p, p.rushing_att, p.rushing_yds, p.rushing_tds)


So from that I wasn't sure.  All I have is this so far

games = nflgame.games(2018,  week=10)
def nice_score(self)
print '%s vs %s is over. %s wins!' % (g.home, g.away, g.winner)
      	for g in active:
           h, sh, a, sa = g.home, g.score_home, g.away, g.score_away
            print '%s :: %s (%d) vs. %s (%d)' % (g.time, h, sh, a, sa)


Then I need it to export to excel automatically.  This is what I have on that area.  I have looked over the API documentation but I just don't have enough experience in programming to do this on the fly I guess. 

nflgame.combine(nflgame.games(2018)).csv("2018.csv")

My goal is to have the scores from each week populate automatically in my sheet (most likely google sheets) because I'm running a knockout pool with almost 1000 entries.   Thanks for any help.

**Comment by scockster** [comment]
Can I reopen this question?

**Comment by mickeelm** [comment]
I have no idea why this was closed. Give me the format you want (awayteam,awayscore,hometeam.homescore maybe?) and I can give you a script.

**Comment by derek-adair** [comment]
Oh sorry that was rude. i meant to close w/ comment "re-open" if you have more questions!

Definitely a welcome environment to submit questions here.  I'm just OCD.

**Comment by derek-adair** [comment]
HA! I thought someone answered your question as well... it was you...

**Comment by mickeelm** [comment]
Not sure I follow here - @scockster asked, I answered...or is that what you meant? :)

**Comment by mickeelm** [comment]
Well, OP seems to have left the building but I guess both issues can be closed.
