### ISSUE TITLE
ANNOUNCEMENT: Dropping python 2 support without a volunteer to maintain

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#61]
As it stands right now I will not be contributing to this projects python 2 code base.  If there is someone who is interested in maintaining the python 2 code, please reach out to me via email and we can discuss what that might look like.  I'm inclined to drop support altogether.  Depending on feedback from the community here that may necessitate a fork.  I know it's possible to detect python version, and [support both 2/3](https://python-future.org/compatible_idioms.html), i'm just not sure its worth it.

I plan to code towards 3.7.2.  If anyone has any qualms or feedback towards a specific python 3 version, I'm all ears.  However, I'm inclined to support the latest releases.  I will be reviewing https://github.com/derek-adair/nflgame/pull/40 and hopefully merging to master without any real problems.

**Comment by hugovk** [comment]
Python 2 reaches EOL on 1st January 2020, and many projects are dropping support on or before that date: https://python3statement.org.

**Comment by derek-adair** [comment]
ITS HAPPENING... PYTHON 2 IS DYING!!!!!!!!!!!

**Comment by ochawkeye** [comment]
I'm a holdout. I'll likely be running this snapshot for an indefinite amount of time.

**Comment by derek-adair** [comment]
Ya there are tons of people who will never switch.  I'm not sure I would if it were a personal project.

**Comment by valetechsolutions** [comment]
The first thing I tried to do was use this in a Jupyter notebook and then was sad.

**Comment by derek-adair** [comment]
@valetechsolutions - you are welcome to try out the [python 3 pull request](https://github.com/derek-adair/nflgame/pull/40) 

I will be addressing this ASAP to get it into a distribution.

**Comment by derek-adair** [comment]
You can easily test out new python3 version by explicitly asking for the alpha release.

`pip intsall nflgame-redux==2.0.1a1`  PLEEEASE help me poke around.  First pre-season game is tonight so you will be able to do more than just _search_schedule() for 2019 games.

**Comment by derek-adair** [comment]
@ochawkeye - even with python2 EOL?

**Comment by ochawkeye** [comment]
Is Guido going to sneak into my house and uninstall Python 2.7?

**Comment by hugovk** [comment]
No, but I recommend installing Python 3 and setting it as the default `python`.

**Comment by ticklingthedata** [comment]
Guys I'll be installing 2.0.1a1 and playing a bit with it.

Feel free to shoot any modules/functions/stuff you think worth testing.
