### ISSUE TITLE
Annual kick off reminder

### ISSUE THREAD

**Issue by ochawkeye** [derek-adair/nflgame#62]
Not working for you?  Just a reminder that updating your schedule will tend to fix lots of stuff.

`python c:\Python27\Scripts\nflgame-update-schedule --year 2019`

```
C:\Users\Ben>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nflgame
>>> for game in nflgame.games(2019, 0, kind='PRE'):
...     print game
...
DEN (14) at ATL (10)
>>>
```

**Comment by Boblyng** [comment]
Thanks for the reminder lol. Forgot this last year and couldn't change the season in the league.
