### ISSUE TITLE
current week in live.py

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#64]
[This endpoint](http://www.nfl.com/feeds-rs/currentWeek) returns the current week.  I'm going to be watching this in the pre season but i think we can replace the added scheduling logic that we put in (#3  and the relevant [code it introduced](https://github.com/derek-adair/nflgame/commit/4522f650612296120354c6a8f5d83430522ab361)).

**Comment by derek-adair** [comment]
Forgot to link this to the code.

@mickelm This should revert your (oh so clever) hard work, but not the logic that selectively updates the schedule weekly.

**Comment by mickeelm** [comment]
That's perfect, no need to keep my old code when we have an official source of truth. Good catch!

**Comment by derek-adair** [comment]
Fixed somewhere...
