### ISSUE TITLE
API doc link is dead

### ISSUE THREAD

**Issue by hosler** [derek-adair/nflgame#65]
Hi. awesome project by the way. http://nflgame.derekadair.com/ link in readme points to non existent page

**Comment by derek-adair** [comment]
Which page is missing? It seems to be working for me.

**Comment by hosler** [comment]
you are correct. the problem appears to be on my end.

**Comment by derek-adair** [comment]
For posterity;

Changing the cname from http://{uri} to just {uri} fixed this.
