### ISSUE TITLE
API documentation docs occassionally dont work for some F*(&ing reason D:

### ISSUE THREAD

**Issue by ticklingthedata** [derek-adair/nflgame#67]
Hi,

The package API doc link is broken: http://nflgame.derekadair.com/

It could be great if you fix it by providing the working link ;)

Thanks.

**Comment by bjostad** [comment]
This URL is working for me, just as it did when reported in #65.

**Comment by ticklingthedata** [comment]
Thanks @bjostad. 

PS: the link should be updated in the package Readme.

**Comment by derek-adair** [comment]
Could you please clarify? i cant find the broken link.

**Comment by ticklingthedata** [comment]
Link seems to be ok now. I remember trying to access to the api doc in documentation section, but was given a 404. That happened at least 2 or 3 times yesterday. 
Section of the doc containing the link:
https://github.com/derek-adair/nflgame/blob/master/README.md#documentation-and-getting-help

**Comment by derek-adair** [comment]
Someone else reported this so it can't be a coincidence.  The api docs are hosted in my s3 instance its likely that its not configured properly.

I *know* https is broken and will result in an infinite spinner.  I need to figure out how to configure cloudfront for s3 https, alas, I have more pressing matters.

**Comment by derek-adair** [comment]
[This](https://thenewstack.io/how-to-set-up-your-s3-bucket-with-https-in-an-hour/) is the guide i used but I've had no luck with it so far.

**Comment by ticklingthedata** [comment]
May be you can host it in `readthedocs`. Personally, my preferred format.

**Comment by hosler** [comment]
the link doesnt work for me on my internet, but it WILL work for me on my cell phone. I think this is an amazon or DNS issue

**Comment by derek-adair** [comment]
I'll glance over the DNS and S3 configs.  Is there a specific behavior happening?

**Comment by hosler** [comment]
my web client cant resolve the host nflgame.derekadair.com. I'm on a linux box. one of my coworkers is able to resolve the host and he is on windows box. if I follow the link that your domain is CNAME to (http://nflgame.derekadair.com.s3-website-us-east-1.amazonaws.com) then i can access

**Comment by derek-adair** [comment]
weird indeed....... any suggestions on where to look? did i fuck up the CNAME?

**Comment by bjostad** [comment]
Interesting, CNAME seems to resolve properly for many locations here: (https://www.whatsmydns.net/#CNAME/nflgame.derekadair.com)

I'm able to resolve it from OSX, Windows and CentOS machines, some that are in different physical locations, but I also haven't run into this problem (yet, at least).

**Comment by hosler** [comment]
does your cname entry include the "http://" in it?

**Comment by derek-adair** [comment]
`
nflgame.derekadair.com. | CNAME | 120 | http://nflgame.derekadair.com.s3-website-us-east-1.amazonaws.com.`

**Comment by hosler** [comment]
that might be the issue. try taking out the http://

**Comment by derek-adair** [comment]
try now, it should be live.

**Comment by hosler** [comment]
yup. works good for me now

**Comment by derek-adair** [comment]
nice.  thx for the help diagnosing.
