### ISSUE TITLE
Cannot Update Players/Schedule due to httplib2 error

### ISSUE THREAD

**Issue by Coop197823** [derek-adair/nflgame#69]
I am having some issues running the update player/scheule code nfl game.  specifically after I installed nflgame redux (pip install nflgame-redux) and then run the line C:\Python27\ArcGIS10.7\Lib\site-packages\nflgame\update_players.py, I get an error in line 51, import httplibs, No Module named httplib2.  I have verified through the pip install (see attached) that httplib2 installed correctly.  Any other reason for the error?

![httplib2 error](https://user-images.githubusercontent.com/5271425/62823127-abc8ea80-bb5b-11e9-88d5-a9c0d4da532c.png)

![Pip Install](https://user-images.githubusercontent.com/5271425/62823093-e54d2600-bb5a-11e9-8bdb-a9aac82dc462.png)

**Comment by derek-adair** [comment]
Can you try it w/ the new alpha release (which is python 3).

You need to specify the alpha as pypi doesn't factor those in as a release.

`pip install nflgame-redux==2.0.1a1`

**Comment by Coop197823** [comment]
I installed python 3.7.4 and ran the install code.  However now when I run C:\Python37\Lib\site-packages\nflgame\update_players.py, i get an error:

![locationerror](https://user-images.githubusercontent.com/5271425/62824005-e172d100-bb65-11e9-92a4-5799339c638f.png)


on a bright note, I did get the player update to work for python 2.7 by running in the IDLE the code:

import nflgame.update_players
nflgame.update_players.run()

**Comment by derek-adair** [comment]
In python2.7 you should try running it through the script thats added to the path.

`$>nflgame-update-players`

Closing because this seems resolved...ish.
