### ISSUE TITLE
IRC channel is dead

### ISSUE THREAD

**Issue by hosler** [derek-adair/nflgame#71]
IRC channel is dead. Yall got a discord or something?

**Comment by derek-adair** [comment]
Ooof ya, i noticed that was still in there.  I'm not 100% interested in participating in a chat room at the moment I'm quite busy and would not really be able to participate anyways.

If someone were interested in setting one up I'd be happy to link it and join when i'm less busy.

**Comment by hosler** [comment]
i created https://discord.gg/8mBubF if anyone would like to join me
