### ISSUE TITLE
Getting error with "new_http" in update_players()

### ISSUE THREAD

**Issue by RealJWise** [derek-adair/nflgame#75]
File "C:\ProgramData\Anaconda3\lib\site-packages\nflgame\update_players.py", line 458, in fetch
    resp, content = new_http().request(purl, 'GET')
NameError: name 'new_http' is not defined

This looks like it was mentioned in #40 but I don't see it resolved anywhere.

Note, this is in the py3 build.

**Comment by derek-adair** [comment]
Try this out on the last push i did to dev branch OR `pip install nflgame-redux==2.0.1b2`
