### ISSUE TITLE
Issue loading game data from 2018 season wk 4 - in py3 branch

### ISSUE THREAD

**Issue by rysarmstr** [derek-adair/nflgame#83]
Apologies if I have missed an explanation for what is happening here, but when I try to query 2018 data week by week I keep stalling out on week 4 of 2018. When I request the bulk of 2018 I have no issues
Specifically request week 4 like:
`games = nflgame.games(2018, week=4)`

I get the error `'NoneType' object is not iterable` at line 224 `return list(games_gen(year, week, home, away, kind, started))`

Am I systematically doing something wrong here? Thanks.

**Comment by pwu97** [comment]
getting the same error. 2018 and 2019 dont work right now.

**Comment by derek-adair** [comment]
I just pushed some updates from dev to py3.  But i think this is likely related to #68.

**Comment by derek-adair** [comment]
nflgame._search_schedule(year=2018, week=4) is returning an empty set.  Investigating....

**Comment by derek-adair** [comment]
The schedule data was corrupted somehow.  The fix has been pushed to the dev branch.  I will be deploying this fix and some other things on PyPi this week.  You can install this branch [locally](https://stackoverflow.com/questions/15031694/installing-python-packages-from-local-file-system-folder-to-virtualenv-with-pip) in the meantime if you need.

**Comment by derek-adair** [comment]
Can you confirm this is no longer happening on the latest release?

`pip install nflgame-redux=2.0.1b1`

**Comment by ryscar13** [comment]
Ran without error! Thanks!

**Comment by ryscar13** [comment]
Following up on this... I am now seeing two separate issues. This same code snippet works fine for 2016

For season 2017
`games = nflgame.games(2017,week=1)`
still gives an empty object.

For 2018 I'm receiving an error at a different place:
`plays = nflgame.combine_plays(games).filter(team=team)`
yields,
`KeyError: 'drives'`

**Comment by pwu97** [comment]
can confirm what ryscar13 said. i scraped the csv files for 2009-2017 games if you need it.

**Comment by derek-adair** [comment]
@pwu97 what do you mean scraped the csv files?

**Comment by lollipoll** [comment]
I ran into the 2017 week 1 problem as well. Does it have something to do with the postponed TB@MIA game? When I try to pull data from that game specifically, it gives me the exact same AttributeError as when I pull the entire week. All of the other games work as expected.

**Comment by emuelle2** [comment]
Using version nflgame-redux==2.0.1a1 (Python 3.7), I can run 2018 week 4 by setting week number to 4.142857142857142. 2017 week 1 also works without issue for me in this version. This returns values for games:
    wk=nflgame.games(2018, week=4.142857142857142)
    for t in wk:
        msg = '%s %s at %s %s; away passing yds = %s, home passing yds = %i'
        print(msg % (t.away, t.score_away, t.home, t.score_home, t.stats_away.passing_yds, t.stats_home.passing_yds))

**Comment by derek-adair** [comment]
Ya these all seem to be related to the schedule being corrupt and is exposed by the recent changes in nflgame.games.

You can see the latest releases here: https://pypi.org/manage/project/nflgame-redux/releases/

**Comment by Cjaimesg** [comment]
Hi, i found in the .json this 

"2017091006",
   {
    "away": "TB",
    "day": 10,
    "eid": "2017091006",
    "gamekey": "57241",
    "home": "MIA",
    "meridiem": "PM",
    "month": 9,
    "season_type": "REG",
    "time": "1:00",
    "wday": "Sun",
    "week": 1,
    "year": 2017
   }

This match not exist http://www.nfl.com/liveupdate/game-center/2017091006/2017091006_gtd.json 
This match have been moved to 2017111911 - http://dailydolphin.blog.palmbeachpost.com/2017/09/06/nfl-moves-miami-dolphins-game-vs-tampa-bay-buccaneers-to-nov-19/

http://www.nfl.com/liveupdate/game-center/2017111911/2017111911_gtd.json

**Comment by derek-adair** [comment]
Ya i'll probably just have to manually correct this until I have time to adjust schedule.json dynamically.

**Comment by Cjaimesg** [comment]
I Can help you to update Schedule.json

**Comment by derek-adair** [comment]
PRs for this would be greatly appreciated.  I will set aside time this week to do some pushes that i've been putting off.

**Comment by morelandjs** [comment]
This fixes the issue, but I wouldn't say it's a particularly great fix.
`                     assert game.eid is not None
                 game.data['gcJsonAvailable'] = True
-            except ValueError:
+            except (ValueError, AttributeError):
                 return None
`

**Comment by derek-adair** [comment]
I'll get that in there for a quick fix.  I've been pulled away from this project briefly and will be fixing things before the new year/playoffs.

**Comment by derek-adair** [comment]
closing b/c schedule. should be fixed.
