### ISSUE TITLE
Error updating players on fresh py3 install

### ISSUE THREAD

**Issue by tomweingarten** [derek-adair/nflgame#84]
When attempting to update players on a fresh install of nflgame-redux using Python 3, I get the following error. This is using version 2.0.1a5.

Setting year to 2019 and week to 2 fixes this problem. This leads me to believe the problem is caused by nflgame trying to fetch data for games that have not yet occurred yet.

~/.local/bin/nflgame-update-players 
Updating (2019, 'REG', 3)
Loading games for REG 2019 week 3
Traceback (most recent call last):
  File "/home/homedir/.local/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/home/homedir/.local/lib/python3.5/site-packages/nflgame/update_players.py", line 370, in run
    players = dict(players_from_games(metas, games))
  File "/home/homedir/.local/lib/python3.5/site-packages/nflgame/update_players.py", line 249, in players_from_games
    for d in g.drives:
  File "/home/homedir/.local/lib/python3.5/site-packages/nflgame/game.py", line 474, in __getattr__
    self.__drives = _json_drives(self, self.home, self.data['drives'])
KeyError: 'drives'

**Comment by derek-adair** [comment]
Let me merge updates from dev branch into py3 branch.  I should probably delete py3 as that was really just a first pass at updating from 2.7.

**Comment by derek-adair** [comment]
I'll look into this, thanks for the report.

**Comment by derek-adair** [comment]
Fix is pushed to dev branch, i'll be deploying this fix sometime this week.

**Comment by brianzhou13** [comment]
just hit this as well.

What's your thought of merging this fix into the `py3` branch as well. The README directs users to use the `py3` install for python3 compatibility, and I think that branch could benefit with this fix (if it's easy to merge in).


Thanks again for helping maintain!

**Comment by derek-adair** [comment]
Ya i probably shouldn't have added that to the readme.  I'll update the py3 branch but also fix the references in the readme.

All active development will take place on the dev branch going forward.
