### ISSUE TITLE
nflgame in pycharm

### ISSUE THREAD

**Issue by wickedflow** [derek-adair/nflgame#85]
Is it possible to use nflgame-redux in PyCharm for python 3? I'm trying and it seems that I can't import a package that has a hyphen in it.

**Comment by derek-adair** [comment]
closing as this is beyond the scope of this project.  You may be trying to import nflgame-redux.  That is just the namespace on pypi, which is different than the local namespace that is nflgame.

If you are importing nflgame-redux change that to just nflgame, its meant to be a drop in replacement for the original project, if not try and report the hyphen issue to pycharm.

**Comment by wickedflow** [comment]
sorry, i'm a novice to python so forgive my ignorance.  when i try to import nflgame, it says it's only for python 2, and i'm on three

**Comment by samthaman** [comment]
you'll want to _install_ nflgame-redux, but you'll want to _import_ nflgame

installing eg: `pip install nfl-redux` or install the package through pycharm

using: 
`import nflgame

games = nflgame.games(2019)
players = nflgame.combine_game_stats(games)
for p in players.rushing().sort('rushing_yds').limit(5):
    msg = '%s %d carries for %d yards and %d TDs'
    print(msg % (p, p.rushing_att, p.rushing_yds, p.rushing_tds))`

**Comment by wickedflow** [comment]
that works! the issue I have is that when i try to run that, nothing pops up, and at the bottom it says "Executing Code in Console" continuously

**Comment by samthaman** [comment]
Can you post your code and also describe how you're trying to run it? (EG: from the terminal 'python3 mynflscript.py' or in Pycharm using the 'run' button)

**Comment by wickedflow** [comment]
I try to run
'games = nflgame.games(2019)
players = nflgame.combine_game_stats(games)
for p in players.rushing().sort('rushing_yds').limit(5):
    msg = '%s %d carries for %d yards and %d TDs'
    print(msg % (p, p.rushing_att, p.rushing_yds, p.rushing_tds))'

and my error is 

Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\UA967HS\PycharmProjects\PythonAtoZforDSci\venv\lib\site-packages\nflgame\__init__.py", line 354, in combine_game_stats
    [g.players for g in games if g is not None])
  File "C:\Users\UA967HS\PycharmProjects\PythonAtoZforDSci\venv\lib\site-packages\nflgame\__init__.py", line 354, in <listcomp>
    [g.players for g in games if g is not None])
  File "C:\Users\UA967HS\PycharmProjects\PythonAtoZforDSci\venv\lib\site-packages\nflgame\game.py", line 470, in __getattr__
    self.__players = _json_game_player_stats(self, self.data)
  File "C:\Users\UA967HS\PycharmProjects\PythonAtoZforDSci\venv\lib\site-packages\nflgame\game.py", line 825, in _json_game_player_stats
    if category not in data[team]['stats']:
KeyError: 'stats'

**Comment by samthaman** [comment]
That might be a package specific thing, and honestly i'm not that familiar with this package yet, but , have you run: 
```
nflgame-update-players
```
from the command line at least once before trying to run your script? In pycharm, just open the terminal inside your project and let that update your player data first.

**Comment by wickedflow** [comment]
btw thanks for your help. 

i believe it's updated, but when i try to week2 = nfl.games(2019, 2)

the output is 

[<nflgame.game.Game object at 0x00000204EC18DF08>, <nflgame.game.Game object at 0x00000204EC31C8C8>, <nflgame.game.Game object at 0x00000204EC667EC8>, ...

**Comment by samthaman** [comment]
did you mean to type nflgame.games? (not nfl.games) 

Also I think you're printing the game object itself not the data in it, so you'll need to do some extra parsing step that isn't happening now. What you're outputting is basically where that particular 'game' lives in memory, not the information in it.  Please post the code the created that error and I'll try to take a look.

**Comment by derek-adair** [comment]
This is a bug actually.  The fix will be pushed shortly.

**Comment by derek-adair** [comment]
`pip install nflgame-redux==2.0.1b1` should fix the update players bug.
