### ISSUE TITLE
Is the virtualenv from the install instructions really needed?

### ISSUE THREAD

**Issue by schroek3** [derek-adair/nflgame#86]
I feel like it might be slowing some stuff down, and I'd probably prefer to get rid of it if it isn't necessary.

**Comment by derek-adair** [comment]
Nope! It's just how I recommend and prefer to do things.  It helps isolate projects and ensure no conflicts.

-----------------

_Closing this b/c i'm super OCD_ - However, if you have any evidence of this slowing down i'd be glad to help debug, reopen this and potentially submit an bug to virtualenv (they'd love to know their project is slowing things down).
