### ISSUE TITLE
Cannot run nfldb-update

### ISSUE THREAD

**Issue by scottismyname** [derek-adair/nflgame#89]
Here is the output:
`Traceback (most recent call last):
  File "/home/scott/.local/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "/home/scott/.local/lib/python3.6/site-packages/nfldb/__init__.py", line 61, in <module>
    from nfldb.db import __pdoc__ as __db_pdoc__
  File "/home/scott/.local/lib/python3.6/site-packages/nfldb/db.py", line 2, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'`

For rerference, I followed the instructions to install nfldb from the old BurnSushi repository (including setting up postgres, etc).  Once that was finished, I installed the new redux (python3 version).

I'm sure this is a setup problem somehow, but not sure where to go from here.

**Comment by scottismyname** [comment]
Do I need python2 and python 3 installed?

**Comment by NickBenthem** [comment]
Type pip install ConfigParser into your terminal / command line (Linux/Mac v. Windows)

**Comment by scottismyname** [comment]
I have done this but to no avail.  I tried from scratch on ubuntu 19.10 and I cannot for the life of me get this to work.  If anyone has a guide for getting this to work, I'm all ears.

Until them I'm stuck on the old version and trying to manually fix things as they break using the python 2.7 branch.  @ochawkeye is your repo up to date with the changes you've had to make?

**Comment by derek-adair** [comment]
There are various breadcrumbs/clues you can trace throughout these projects.  If there is still sufficient interest I will considering bringing nfldb under my control as well... For now I cant personally justify this effort.
