### ISSUE TITLE
My thoughts on Andrew's nfl* code and where to go from here

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#9]
There are two other projects that are driven by nflgame...  [nfldb](burntsushi/nfldb) and [nflfan](burntsushi/nflfan).  This is something I was unaware of upon discovery and well into the development of one of my projects.  Initially my thoughts were to fork all projects and unify them under one code base, in an entirely new namespace.  However, i'm not so sure that solves much of anything and it would certainly bloat the package.  I'm shelving this notion for now, but i'm definitely considering .  Anyways nflfan seems to be the culmination of Andrew's work.

One of the reasons Andrew has abandoned this project is the copious amount of VERY low level issue's filed.  There are numerous issue's/questions/suggestions that are either a) filed in the wrong repository altogether or b) a direct result of not being aware of the suite of projects contributed by Andrew.

This is a documentation problem...
There are no references to nfldb or nflfan ANYWHERE in the documentation for this project.  In the NFLdb repository there is mention of nflgame, but man i feel like this should HIT YOU OVER THE FREAKING HEAD.   Something as simple as a table of contents in each description.md would go a long way.

**Comment by mickeelm** [comment]
Actually he has/had five projects. [nflgame](https://github.com/BurntSushi/nflgame), [nfldb](https://github.com/BurntSushi/nfldb), [nflvid](https://github.com/BurntSushi/nflvid), [nflfan](https://github.com/BurntSushi/nflfan) and [nflcmd](https://github.com/BurntSushi/nflcmd).

nfldb is clearly mentioned in README.md of this project..? nflvid in that section, too. Do I misunderstand something here? Do you mean the code, specifically?

Writing a description of that "stack" of projects in the README here would be a good idea, though. Also mentioning that those projects are abandoned (until someone forks them, if that happens) and may or may not work with this new fork.

**Comment by derek-adair** [comment]
Oh hey, it is mentioned.  Not sure how i missed that.

**Comment by mickeelm** [comment]
A rewrite of the readme is necessary anyway. It does contain a dead link or two (to Andrew's site). Also it is still written in "I-form" from Andrew. I think that a rewrite, maybe with a FAQ early on, is a good idea to further establish that this is a self-living _fork_. Of course some credit to Andrew is still nice to have.

So if we have a good idea (it seems like you've done some digging) on which are the most common questions and have answers to these early on in the readme (FAQ), I think that would be a good thing.

Also, Andrew has put in a lot of effort and tremendous amounts of patience. Personally (this might sound harsh but I think it's more a matter of respect for people's time) I think that before posting an issue, it is one's duty to at least _try_ to get an answer by reading the docs and/or previous issues. Normal forum etiquette.

So he took the step of, after a few years, stating in the readme not to send emails but use the issue tracker. I'd like to take that one step further and having something like:

> 
> If you have a question about the functionality of nflgame, please read through the FAQ, documentation and previous issues for answers. Still can't find an answer? No worries, file an issue.
> 
> Have you found a bug? Please report an bug in the issue tracker and help make nflgame better :)
> 
> Do you have improvement suggestions? Please file an issue and help make nflgame better :)

If needed, the "no-email"-thingy should be there too but at this point I don't know if it's necessary. In `setup.py` I think it is, Andrew's email is still there. I think that we should remove it and just keep his name (he did write it, after all).

**Comment by tabalint** [comment]
Where are you with transposing the issues from the old repo to this one? I'm between jobs and an NFL data fan so I'm happy to help make this Python3 friendly and help make it useful to this and future seasons.

At least the important issues. I'd be happy to tackle specific problems with the transition or with recent updates.

**Comment by derek-adair** [comment]
Honestly a lot of those issues are just old and SO many config issues; its pretty hard for me to nail down what bugs would be worthy over here.  I've not bothered transposing any of them as  this project is liable to change.... A LOT... in the next year.  I'm considering all kinds of different avenues to take this project. Including but not limited to;

* Combining ALL of andrew gallants code under one roof (probably not)
* Removing json.tar.gz stores in favor of something more robust
* Removing the caching of the nfl api (probably not)
* updating the stat data model to fit the new feeds-rs we found.

You're welcome to try out the python 3 branch and build the code OR just download the alpha `pip install nflgame-redux==2.0.1a1`

Any crucial bugs or features you feel are worthy of submitting please go ahead and do so.

I plan on creating a survey to catalog how people are using this particular project and this will likely influence where it goes.

**Comment by donlaur** [comment]
I would be willing to pay a python developer if they are able to get it setup on a unix server or a hosted server and have the data go into postgresql.  I want to use this for a fantasy sports site and make a frontend that pulls out postgresql with this running in the background every X seconds.  Let me know at donlaur@gmail.com.

**Comment by derek-adair** [comment]
@donlaur I'll reach out to you today.  This is something I would be interested in, depending on the details and such.

**Comment by derek-adair** [comment]
Email sent - i'm capable of doing whatever you (or anyone) needs and i welcome people funding me to get this project in better shape.  i thought about adding a donation option.  Also thought about throwing this all up behind an api and charging for that (while the nfldb/nflgame w/o api would remain FOSS)
