### ISSUE TITLE
Play Data is missing Player Name

### ISSUE THREAD

**Issue by Coop197823** [derek-adair/nflgame#94]
I have come across another error as it relates to issue [#90](https://github.com/derek-adair/nflgame/issues/90) the play level data for a player.  It seems the play level stats are populated when running the code but the payer name is not being populated.  I assume it is related to the change in the nfl.com API
```
import nflgame

week = 9
games = nflgame.games(2019, week=week)
play = nflgame.combine_plays(games)

for play in play.filter(passing_incmp__gt=0):
    for player in play.players:
        if player.player.position in ['WR', 'TE', 'RB']:
            row = [player, player.player.team, player.player.position,  play.passing_incmp_air_yds] 
            print(row)
```

Snippet output  of code:
```
[<nflgame.player.PlayPlayerStats object at 0x00000000051064E0>, 'ARI', 'TE', 22]
[<nflgame.player.PlayPlayerStats object at 0x0000000005118B38>, 'SF', 'TE', 5]
[<nflgame.player.PlayPlayerStats object at 0x0000000005120048>, 'ARI', 'WR', 11]
[<nflgame.player.PlayPlayerStats object at 0x0000000005120358>, 'ARI', 'WR', 5]
[<nflgame.player.PlayPlayerStats object at 0x0000000005120F28>, 'SF', 'TE', 18]
[<nflgame.player.PlayPlayerStats object at 0x00000000051332B0>, 'ARI', 'WR', 5]
[<nflgame.player.PlayPlayerStats object at 0x0000000005144048>, 'ARI', 'WR', 6]
[<nflgame.player.PlayPlayerStats object at 0x000000000514D0B8>, 'SF', 'RB', 0]
[<nflgame.player.PlayPlayerStats object at 0x000000000514DEB8>, 'SF', 'WR', 13]
```

**Comment by blcooley** [comment]
It looks to me like the name is there. What seems to be happening is that the print function is giving you the results of the `player.__repr__()` call, which returns a representation of the player object. You should be able to change your first element in row to `player.name` to get the name string. Alternatively you can call `player.__str__()` and you'll get the name, but I think the other way is more readable. YMMV.

**Comment by Coop197823** [comment]
Thanks that seems to help, even though we still seem to be missing teams from issue 90

**Comment by Coop197823** [comment]
@blcooley Thanks for the help.  I have followed the instructions to fix the games issue, but still have one last issue.  
```

import nflgame

week = 9
games = nflgame.games(2019, week=week)
play = nflgame.combine_plays(games)

for play in play.filter(passing_incmp__gt=0):
    for player in play.players:
        if player.player.position in ['WR', 'TE', 'RB']:
            row = [player.name, player.player.team, player.player.position,  play.passing_incmp_air_yds] 
            print(row)
```
The code runs perfectly with no errors and all the teams popping up.  Now, when I run the second piece of code:

```
for play in play.filter(receiving_rec__gt=0):
    for player in play.players:
        if player.player.position in ['WR', 'TE', 'RB']:
            row = [player.name, player.player.team, player.player.position,  player.receiving_yds-player.receiving_yac_yds] 
           print(row)
```
it runs most of the way through (below is a snippet):
```

['M.Williams', 'ARI', 'TE', 2]
['C.Kirk', 'ARI', 'WR', -2]
['R.Dwelley', 'SF', 'TE', 1]
['E.Sanders', 'SF', 'WR', 6]
['P.Cooper', 'ARI', 'WR', -1]
['L.Fitzgerald', 'ARI', 'WR', 0]
['K.Drake', 'ARI', 'RB', -1]
['M.Breida', 'SF', 'RB', 3]
['R.Dwelley', 'SF', 'TE', 4]
```

 until it hits and returns this error (I expect about halfway through the pull):

```
Traceback (most recent call last):
  File "C:\Python37\Scripts\GrabPythonData.py", line 13, in <module>
    if player.player.position in ['WR', 'TE', 'RB']:
AttributeError: 'NoneType' object has no attribute 'position'
```

I believe this is usually indicative if there is a game update issue, but if it works for other weeks as well as for other data pulls, I am not sure why is is not getting all the data.  Any thoughts on what I need ot do?

**Comment by blcooley** [comment]
The error means that player.player is `None`. 

Looking at the code in `player.py`, the most likely reason is that the PlayerStats object (i.e., the first player) has a `player_id` that isn't in the list of players for whatever reason. When that happens, the player is set to `None`.

You could skip such players and avoid the crash by adding an extra condition to your if statement.

You could also print out the playerid to figure out what player is not in the players map to get more information to drill down. For example:

```
for play in play.filter(receiving_rec__gt=0):
    for player in play.players:
        print(player.playerid)
        if player.player is not None and player.player.position in ['WR', 'TE', 'RB']:
            row = [player.name, player.player.team, player.player.position,  player.receiving_yds-player.receiving_yac_yds] 
            print(row)

```

**Comment by Coop197823** [comment]
@blcooley Thanks again for your insights.  It was in fact a player with the gsisid of 00-0031838 that was not in the player list.  I created a dummy variable with that id in the players.json and it ran without issues.  Again, ty for taking the time to help explain how to troubleshoot the code!

Would there be a better way to skip that player entirely and keep running the code if that in fact happens again?

**Comment by blcooley** [comment]
@Coop197823 
This line (see the code snippet in my last comment for context) will skip any players who aren't in the player map:

`if player.player is not None and player.player.position in ['WR', 'TE', 'RB']:`

**Comment by derek-adair** [comment]
Can this be closed?

Is there anything to be done to player.py to make this more robust?
