### ISSUE TITLE
data appears incomplete for three specific weeks (including 2019 week 16)

### ISSUE THREAD

**Issue by opi9a** [derek-adair/nflgame#99]
I cannot get data for 2019 week 16 (or for two other weeks in previous years).
```
>>> import nflgame
>>> len(nflgame.games(year=2019, week=15))
16
>>> len(nflgame.games(year=2019, week=16))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gav/anaconda3/lib/python3.7/site-packages/nflgame/__init__.py", line 224, in games
    return list(games_gen(year, week, home, away, kind, started))
  File "/home/gav/anaconda3/lib/python3.7/site-packages/nflgame/__init__.py", line 271, in gen
    g = nflgame.game.Game(**info)
  File "/home/gav/anaconda3/lib/python3.7/site-packages/nflgame/game.py", line 315, in __new__
    game.data = json.loads(game.rawData.decode('utf-8'))[game.eid]
AttributeError: 'NoneType' object has no attribute 'decode'


```
I get the same error for `year=2017, week=1` and `year=2018, week=16`.  All other weeks from 2009 on are ok.

Thanks.

**Comment by trojanguard25** [comment]
While I can't say what is going on with the 2017 and 2018 seasons, there was a comment on another issue regarding the 2019 issue in #98, specifically comment
https://github.com/derek-adair/nflgame/issues/98#issuecomment-568932261
Basically, you should try running the `nflgame-update-schedule` from the /scripts/ folder with `--rebuild` flag.

**Comment by opi9a** [comment]
Great that works, thanks.

As an aside, having installed using `pip install nflgame-redux==2.0.1b1` I cannot see a `scripts/` folder as described.

Instead I ran the following from the `nflgame/` home directory:
```
$ python update_schedule.py --rebuild
```

Thanks again

**Comment by Coop197823** [comment]
I also am still having this same issue.  I ran from cmd (@ location Python37\Scripts):

`$ python nflgame-update-schedule  --rebuild`

in my python 37 directory, but the same error still persists as the OP stated.

Any thoughts on what else to try?

**Comment by opi9a** [comment]
You have tried what I did?

**Comment by Coop197823** [comment]
yes, I found the error seemed to be my env variables were pointing to my 27 python and not my 37 python.

However I did notice that players teams did not update correctly.  For instance, when I run code:
```

import nflgame
week = 16
games = nflgame.games(2018, week=week)           
for play in play.filter(passing_incmp__gt=0):
    for player in play.players:
        if player.player is not None and player.player.position in ['WR', 'TE', 'RB']:
            row = [player.name, player.player.team, player.player.position,  play.passing_incmp_air_yds] 
            print(row)
```

Z.Jones shows up with team OAK (instead of BUF for 2018).  So it seems the players have not updated correctly for 2018.

**Comment by ochawkeye** [comment]
`player.player.team` is referencing their current team as it is taken from
the player's current NFL profile.

**Comment by Coop197823** [comment]
Is there a way to specifically match older players to teams?

**Comment by ochawkeye** [comment]
You might try `player.team` instead of `player.player.team`
